al:
  vacancies:
  - chamber: upper
    district: 14
    vacant_until: 2021-07-15
  - chamber: lower
    district: 78
    vacant_until: 2021-07-15
  - chamber: lower
    district: 73
    vacant_until: 2021-07-15
wi:
  vacancies:
  - chamber: lower
    district: 37
    vacant_until: 2021-07-01
us:
  vacancies:
  - chamber: lower
    district: FL-20
    vacant_until: 2021-07-01
  - chamber: lower
    district: NM-1
    vacant_until: 2021-07-01
  - chamber: lower
    district: OH-11
    vacant_until: 2021-07-01
  - chamber: lower
    district: TX-6
    vacant_until: 2021-07-01
  - chamber: lower
    district: LA-2
    vacant_until: 2021-07-01
